variable "prefix" {
    default = "AZURE-POC-SPOKE"
}
variable "resource_group" {}
variable "location" {}
variable "address_space" {}
variable "admin_username" {}
variable "admin_password" {}
variable "ipsec_license" {}
variable "veos_license" {}
variable "ipsec_psk" {}
variable "local_asn" {}
variable "community" {}
variable "peer_tunnel_ip" {}
variable "peer_asn" {}
variable "peer_desc" {}
variable "peer_key" {}
variable "peer_subnet_1" {}
variable "tunnel_ip" {}
variable "tunnel_dest" {}
variable "pub_ssh_key" {}
